# https://docs.codecov.io/docs/codecov-yaml

codecov:
  max_report_age: off

ignore:
  - "./cmd/basic"
  - "./cmd/benchmark_rpc"
  - "./cmd/benchmark_send"
  - "./cmd/chat"

comment: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 20%
        if_not_found: success
    patch:
      default:
        enabled: no
        threshold: 0%
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
